name: 'Manual: Docker Push'

on:
  workflow_dispatch:

  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

env:
  CHATBOT_DOCKER_FILE: Dockerfile

  CHATBOT_IMAGE_NAME: sibedge/chatbot-app

jobs:
  docker-tag:
    name: Docker Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: New Docker Tag
        shell: bash
        run: echo "DEFAULT_DOCKER_TAG=$(echo ${GITHUB_REF##*/} | sed 's/[^a-zA-Z0-9._-]/-/g')" >> $GITHUB_ENV

      - name: Set Docker Tags
        shell: bash
        run: |
          DOCKER_TAGS="${{ env.DEFAULT_DOCKER_TAG }}"
          echo $DOCKER_TAGS > docker_tags.txt
      - name: Upload Docker Tags
        uses: actions/upload-artifact@v3.1.3
        with:
          name: docker-tags
          path: docker_tags.txt

  docker-push-chat-bot:
    name: Chat bot build & push
    needs:
      - docker-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v1

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Download Docker Tags
        uses: actions/download-artifact@v3
        with:
          name: docker-tags
          path: artifact

      - name: Set Docker Tags
        run: |
          DOCKER_TAGS=$(cat artifact/docker_tags.txt)
          echo "DOCKER_TAGS=$DOCKER_TAGS" >> $GITHUB_ENV

      - name: App build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ${{ env.CHATBOT_DOCKER_FILE }}
          tags: ${{ env.CHATBOT_IMAGE_NAME }}:${{ env.DOCKER_TAGS }}
